// Script (C) 2012 by Mark Rosenfelder.
// You can modify the code for non-commercial use; 
// attribution would be nice.
// If you want to make money off it, please contact me.

// Modified by Jason Tamez 2017-2019.

// ==ClosureCompiler==
// @compilation_level SIMPLE_OPTIMIZATIONS
// ==/ClosureCompiler==

var NLEX=150,NSENT=30,word,output,punc=".?!",cat,ncat,catindex="",badcats,syl,nsyl,wisyl,nwisyl,wfsyl,nwfsyl,snsyl,nsnsyl,onetype,monosyl=0,dropoff=50,rew,nrew,badrew,showsyl=!1,slowsyl=!1,tempArray=[],CustomInfo=!1,Customizable=!1,zCounter;
function parseAllInput(){cat=$("#cats").val().split(/\r?\n/);ncat=cat.length;badcats=!1;catindex="";tempArray=[];cat.forEach(function(a){a=a.trim();var b=a.length;0===b?ncat--:3>b||1!==a.indexOf("=")||-1!==a.indexOf("=",2)?(badcats=!0,ncat--):(catindex+=a.charAt(0),tempArray.push(a))});cat=tempArray;var a=$("#syls").val().split(/\r?\n/);syl=parseSyllables(a);nsyl=syl.length;a=$("#wrdi").val().split(/\r?\n/);wisyl=parseSyllables(a);nwisyl=wisyl.length;a=$("#wrdf").val().split(/\r?\n/);wfsyl=parseSyllables(a);
nwfsyl=wfsyl.length;a=$("#sing").val().split(/\r?\n/);snsyl=parseSyllables(a);nsnsyl=snsyl.length;tempArray=$("#rewrite").val().split(/\r?\n/);nrew=tempArray.length;rew={};badrew=!1;var c=0;tempArray.forEach(function(a){var b=a.indexOf("||");if(1>b||b!==a.lastIndexOf("||"))nrew--,badrew=!0;else{var e=a.substring(b+2);a=new RegExp(a.substring(0,b),"g");rew[c.toString()]=[a,e];c++}})}function parseSyllables(a){var c=[];a.forEach(function(a){a=a.trim();""!==a&&c.push(a)});return c}
function handleCategoriesInRewriteRule(a){a=a.split("%%");for(var c=[],b,d,e,f;a.length;){b=a.shift().split("!%");for(e=b.shift();b.length;)f=b.shift(),d=f.charAt(0),d=catindex.indexOf(d),-1!==d&&(e+="[^"+cat[d].substring(2)+"]"),e+=f.substring(1);b=e.split("%");for(e=b.shift();b.length;)f=b.shift(),d=f.charAt(0),d=catindex.indexOf(d),-1!==d&&(e+="["+cat[d].substring(2)+"]"),e+=f.substring(1);c.push(e)}return c.join("%")}function getRandomPercentage(){return Math.floor(101*Math.random())}
function applyRewriteRules(a){var c;for(c=0;c<nrew;c++){var b=rew[c.toString()];a=a.replace(b[0],b[1])}return a}function PowerLaw(a,c){var b;for(b=0;;b=(b+1)%a)if(getRandomPercentage()<c)return b}function PeakedPowerLaw(a,c,b){return.5<Math.random()?c+PowerLaw(a-c,b):c-PowerLaw(c+1,b)}
function Syllable(a){a=syllPatternPick(a);var c;for(c=0;c<a.length;c++){var b=a.charAt(c);var d=catindex.indexOf(b);-1==d?word+=b:(b=cat[d].substr(2),d=0===dropoff?Math.random()*b.length:PowerLaw(b.length,dropoff),b=b.charAt(d),word+=b)}}function syllPatternPick(a){switch(a){case -1:var c=nwisyl;var b=wisyl;break;case 0:c=nsyl;b=syl;break;case 1:c=nwfsyl;b=wfsyl;break;case 2:c=nsnsyl,b=snsyl}a=PowerLaw(c,calcDropoff(c));return b[a]}
function OneWord(a){word="";var c=1,b;Math.random()>monosyl&&(c+=1+PowerLaw(4,50));var d=-1;for(b=0;b<c;b++)onetype?d=-1:1==c?d=2:0<b&&(d=1,b<c-1&&(d=0)),Syllable(d),showsyl&&b<c-1&&(word+="\u00b7");word=applyRewriteRules(word);a&&(word=word.charAt(0).toUpperCase()+word.substring(1));output+=word}function CreateText(){var a,c;for(a=0;a<NSENT;a++){var b=1+PeakedPowerLaw(15,5,50);for(c=0;c<b;c++)OneWord(0===c),c==b-1&&(output+=punc.charAt(PowerLaw(punc.length,75))),output+=" "}}
function CreateLex(a){var c;output+='<div class="lexicon"><table>\n';for(c=0;c<NLEX;c++)0===c%10&&(output+="<tr>"),output+="<td>",OneWord(a),output+="</td>",9==c%10&&(output+="</tr>\n");output+="</table></div>\n"}function CreateLongLex(){var a;for(a=0;a<5*NLEX;a++)OneWord(!1),output+="<br>\n"}
function genall(a,c){if(0!==c.length){var b=c[0],d=1==c.length;var e=catindex.indexOf(b);if(-1==e)d?tempArray.push(applyRewriteRules(a+b)):genall(a+b,c.slice(1));else{var f=cat[e].substr(2);for(b=0;b<f.length;b++)e=f.charAt(b),d?tempArray.push(applyRewriteRules(a+e)):genall(a+e,c.slice(1))}}}
function CreateAll(){tempArray=[];word="";var a,c=syl.concat(wisyl,wfsyl,snsyl);c.sort();var b=c.shift();for(a=[b];0<c.length;){var d=c.shift();d!=b&&(a.push(d),b=d)}d=a.length;for(b=0;b<d;b++)genall("",a[b]);tempArray=tempArray.sort();d="";for(b=0;b<tempArray.length;b++)if(a=tempArray[b],0===b||a!=d)word+=a+"<br>",d=a;output=word;tempArray=[]}
function process(){var a=$("input[type=radio][name=outtype]:checked").val();showsyl=$("#showsyl").prop("checked");slowsyl=$("#slowsyl").prop("checked");onetype=$("#onetype").prop("checked");monosyl=Number($("input[type=radio][name=monosyl]:checked").val());monosyl!=monosyl||1<monosyl?monosyl=1:0>monosyl&&(monosyl=0);dropoff=Number($("input[type=radio][name=dropoff]:checked").val());dropoff!=dropoff||45<dropoff?dropoff=45:0>dropoff&&(dropoff=0);output="";parseAllInput();if(onetype&&(0>=ncat||0>=nwisyl))output=
"You must have categories and syllable types to generate text.";else if(!onetype&&(0>=ncat||0>=nsyl||0>=nwisyl||0>=nwfsyl||0>=nsnsyl))output="You must have categories and all syllable types to generate text.";else if(badcats)output="Categories must be of the form V=aeiou<br>That is, a single letter, an equal sign, then a list of possible expansions.";else if(badrew)output="Rewrite rules must be in the form x||y<br>That is, a rule (x), followed by two vertical bars, followed by a replacement expression (y, which may be blank).";
else switch(a){case "text":CreateText();break;case "dict":CreateLex(!1);break;case "dictC":CreateLex(!0);break;case "longdict":CreateLongLex();break;case "genall":CreateAll()}$("#outputText").html(output)}function calcDropoff(a){return slowsyl?2==a?50:3==a?40:9>a?46-4*a:11:9>a?60-5*a:12}function erase(){$("#outputText").html("")}
function clearBoxes(){$("#cats,#wrdi,#syls,#sing,#wrdf,#rewrite").val("");$("#monoLessFrequent,#dropoffMedium,#textOutput").prop("checked",!0);$("#showsyl,#slowsyl").prop("checked",!1);$("#defaultName").text("")}function prepImport(){$("#importBoxArea").show();$("body").css("overflow","hidden")}function removeImportBox(){$("#importTextBox").val("");$("#importBoxArea").hide();$("body").css("overflow","auto")}
function doImport(){var a=$("#importTextBox").val();a=/--CATS--\n([\s\S]*)\n--REWRITE--\n([\s\S]*)\n--MONO--\n([\s\S]*)\n--MID--\n([\s\S]*)\n--INIT--\n([\s\S]*)\n--FINAL--\n([\s\S]*)\n--FLAGS--\n([01]) ([01]) ([^ ]+) ([^ ]+)/.exec(a);if(null===a)return alert("Incorrect format.");$("#cats").val(a[1]);$("#rewrite").val(a[2]);$("#sing").val(a[3]);$("#syls").val(a[4]);$("#wrdi").val(a[5]);$("#wrdf").val(a[6]);$("#onetype").prop("checked","0"==a[7]?!1:!0);$("#slowsyl").prop("checked","0"==a[8]?!1:!0);
$("#"+a[9]).prop("checked",!0);$("#"+a[10]).prop("checked",!0);syllablicChangeDetection($("#onetype")[0]);alert("Import Successful!");$("#importTextBox").val("");$("#importBoxArea").hide();$("body").css("overflow","auto")}
function doExport(){var a="--CATS--\n"+$("#cats").val()+"\n--REWRITE--\n"+$("#rewrite").val()+"\n--MONO--\n"+$("#sing").val()+"\n--MID--\n"+$("#syls").val()+"\n--INIT--\n"+$("#wrdi").val()+"\n--FINAL--\n"+$("#wrdf").val()+"\n--FLAGS--\n"+($("#onetype").prop("checked")?"1":"0")+" "+($("#slowsyl").prop("checked")?"1":"0")+" "+$("input[name=monosyl]:checked").attr("id")+" "+$("input[name=dropoff]:checked").attr("id");$("#importTextBox").val(a);$("#importBoxArea").show();$("body").css("overflow","hidden");
alert("Export Successful. Copy this for your own records.\n\nHit 'Cancel' when you're done.")}
function saveCustom(){Customizable?CustomInfo&&!confirm("You already have information saved. Do you want to overwrite it?")?alert("Previous information saved."):(localStorage.setItem("CustomCats",$("#cats").val()),localStorage.setItem("CustomRewrite",$("#rewrite").val()),localStorage.setItem("CustomSing",$("#sing").val()),localStorage.setItem("CustomSyls",$("#syls").val()),localStorage.setItem("CustomWrdi",$("#wrdi").val()),localStorage.setItem("CustomWrdf",$("#wrdf").val()),localStorage.setItem("CustomOneType",
$("#onetype").prop("checked")),localStorage.setItem("CustomSlowsyl",$("#slowsyl").prop("checked")),localStorage.setItem("CustomMono",$("input[name=monosyl]:checked").attr("id")),localStorage.setItem("CustomDropoff",$("input[name=dropoff]:checked").attr("id")),CustomInfo=!0,1>$("#predef option[value=-1]").length&&$("#predef").prepend('<option value="-1">Custom</option>'),$("#predef").val("-1"),alert("Saved to browser.")):alert("Your browser does not support Local Storage and cannot save your information.")}
function clearCustom(){Customizable?CustomInfo?confirm("Are you sure you want to delete your saved settings?")?(window.localStorage.clear(),CustomInfo=!1,$("#predef option[value=-1]").remove(),alert("Cleared from browser.")):alert("Settings saved."):alert("You don't have anything saved."):alert("Your browser does not support Local Storage and cannot save your information.")}
function showipa(){word='<span class="desc">Latin:</span>\n<div class="extraGroup">';var a=[161,191,216,248,11360,42786,42891,42928,43824,43872,"x",592,"x",880,886,890,902,904,908,910,931,43877,"x",1024,1162,42560,42624,"x",1329,1377],c=[161,214,246,591,11391,42887,42925,42935,43866,43876,"IPA",767,"Greek and Coptic",883,887,895,902,906,908,929,1023,43877,"Cyrillic",1154,1327,42606,42651,"Armenian",1366,1415],b,d;var e=0;for(d=a.length;e<d;e++)if("x"===a[e])word+='</div>\n<br><br><span class="desc">'+
c[e]+':</span>\n<div class="extraGroup">';else for(b=a[e];b<=c[e];b++)word+='<span title="'+b+": "+getUnicodeName(b)+'">'+String.fromCharCode(b)+"</span>";word+="</div>\n";$("#outputText").html(word)}function advancedOptions(){$("#advancedOpen").toggleClass("closed")}
function defaultme(a){switch(a){case -1:CustomInfo?($("#cats").val(localStorage.getItem("CustomCats")),$("#rewrite").val(localStorage.getItem("CustomRewrite")),$("#sing").val(localStorage.getItem("CustomSing")),$("#syls").val(localStorage.getItem("CustomSyls")),$("#wrdi").val(localStorage.getItem("CustomWrdi")),$("#wrdf").val(localStorage.getItem("CustomWrdf")),$("#onetype").prop("checked","true"===localStorage.getItem("CustomOneType")),$("#slowsyl").prop("checked","true"===localStorage.getItem("CustomSlowsyl")),
$("#"+localStorage.getItem("CustomMono")).prop("checked",!0),$("#"+localStorage.getItem("CustomDropoff")).prop("checked",!0)):defaultme(0);break;case 1:$("#cats").val("C=ptkbdg\nR=rl\nV=ieaou");$("#wrdi").val("CV\nV\nCRV");$("#syls,#sing,#wrdf").val("");$("#onetype").prop("checked",!0);$("#slowsyl").prop("checked",!1);$("#rewrite").val("ki||"+String.fromCharCode(269)+"i");$("#monoLessFrequent,#dropoffMedium").prop("checked",!0);break;case 2:$("#cats").val("C=ptknslrmbdgfvwyh"+String.fromCharCode(353)+
"z"+String.fromCharCode(241)+"x"+String.fromCharCode(269,382,330)+"\nV=aiuoe"+String.fromCharCode(603,596,226,244,252,246)+"\nR=rly");$("#wrdi").val("CV\nV\nCVC\nCRV");$("#syls,#sing,#wrdf").val("");$("#rewrite").val(String.fromCharCode(226)+"||ai\n"+String.fromCharCode(244)+"||au");$("#onetype").prop("checked",!0);$("#slowsyl").prop("checked",!1);$("#monoLessFrequent,#dropoffMedium").prop("checked",!0);break;case 3:$("#cats").val("C=tkpnslrmfbdghvyh\nV=aiueo\nU=aiu"+String.fromCharCode(224,234)+
"\nR=rl\nM=nsrmltc\nK=ptkbdg");$("#wrdi").val("CV\nCUM\nV\nUM\nKRV\nKRUM");$("#syls,#sing,#wrdf").val("");$("#rewrite").val("ka||ca\nko||co\nku||cu\nkr||cr");$("#onetype").prop("checked",!0);$("#slowsyl").prop("checked",!1);$("#monoLessFrequent,#dropoffMedium").prop("checked",!0);break;case 4:$("#cats").val("C=tpknlrsm"+String.fromCharCode(654)+"bdg"+String.fromCharCode(241)+"fh\nV=aieuo"+String.fromCharCode(257,299,363,275,333)+"\nN=n"+String.fromCharCode(331));$("#wrdi").val("CV\nV\nCVN");$("#syls,#sing,#wrdf").val("");
$("#rewrite").val("aa||"+String.fromCharCode(257)+"\nii||"+String.fromCharCode(299)+"\nuu||"+String.fromCharCode(363)+"\nee||"+String.fromCharCode(275)+"\noo||"+String.fromCharCode(333)+"\nnb||mb\nnp||mp");$("#onetype").prop("checked",!0);$("#slowsyl").prop("checked",!1);$("#monoLessFrequent,#dropoffMedium").prop("checked",!0);break;case 5:$("#cats").val("C=ptknlsm"+String.fromCharCode(353)+"yw"+String.fromCharCode(269)+"hf"+String.fromCharCode(331)+"\nV=auieo\nR=rly\nN=nn"+String.fromCharCode(331)+
"mktp\nW=io\nQ=ptk"+String.fromCharCode(269));$("#wrdi").val("CV\nQ"+String.fromCharCode(688)+"V\nCVW\nCVN\nVN\nV\nQ"+String.fromCharCode(688)+"VN");$("#syls,#sing,#wrdf").val("");$("#rewrite").val("uu||wo\noo||ou\nii||iu\naa||ia\nee||ie");$("#slowsyl").prop("checked",!1);$("#onetype").prop("checked",!0);$("#monoLessFrequent,#dropoffMedium").prop("checked",!0);break;case 6:$("#cats").val("S=tspkThfS\nC=kstSplrLnstmTNfh\nI=aoueAOUE\nV=aoiueAOUE\nE=sfSnmNktpTh");$("#rewrite").val("([aeiou])\\1{2,}||$1$1\n([AEOU])\\1+||$1\n(%V{2})%V+||$1\nh+||h\nh(%V%E)\\b||H$1\nh(%V%C{0,2}%V)\\b||H$1\n(%V)h(%V)\\b||$1H$2\n\\bh||H\nh\\b||H\nh||\nH||h\nA||a"+
String.fromCharCode(301)+"\nO||o"+String.fromCharCode(301)+"\nU||u"+String.fromCharCode(301)+"\nE||e"+String.fromCharCode(301)+"\n"+String.fromCharCode(301)+"i||i\n"+String.fromCharCode(301)+"T||"+String.fromCharCode(301)+"t\n"+String.fromCharCode(301)+"S||"+String.fromCharCode(301)+"s\n"+String.fromCharCode(301)+"L||"+String.fromCharCode(301)+"l\n"+String.fromCharCode(301)+"N||"+String.fromCharCode(301)+"n\n(\\B.\\B[aeou])i||$1"+String.fromCharCode(301)+"\n(%C)\\1||$1\n[tkpT]r||r\nn[pTk]||nt\nm[tTk]||mp\nN[ptk]||NT\nk[nmN]||k\np[nN]||pm\nt[mN]||tn\nT[nm]||TN\np[sSh]||pf\nt[fSh]||ts\nT[fsh]||TS\nk[fsS]||kh\nf[sSh]||fp\ns[fSh]||st\nS[fsh]||ST\nh[fsS]||hk\nft||fp\nsT||st\nSt||ST\n([TSLN])[tsln]||$1\n([tsln])[TSLN]||$1\nNT||nT\nTN||tN\nST||sT\nTS||tS\nT||t"+
String.fromCharCode(769)+"\nL||"+String.fromCharCode(314)+"\nS||"+String.fromCharCode(347)+"\nN||"+String.fromCharCode(324));$("#sing").val("SV\nSVE\nSV\nSV");$("#syls").val("SV\nI\nCV\nSVC");$("#wrdi").val("SV\nV\nSVC");$("#wrdf").val("I\nVE\nV\nVE\nSVE\nV\nCV\nVE\nCVE");$("#onetype,#slowsyl").prop("checked",!1);$("#monoRare,#dropoffMedium").prop("checked",!0);break;case 7:$("#cats").val("I=rlmnpbBTRG\nC=pbtdkgnmGszSZwrlBTR\nE=pbtdkgnmGl\nM=pbtdkgnmGrlszSZw\nS=pbtdkg\nN=nmG\nX=szSZwrlnmG\nA=wrl\nV=aIuioe");
$("#rewrite").val("^(b|p)w||$1\n^G||w\n(%X)%X||$1\n(%N|%A)(%S)||$2\n%X(%S%A)||$1\n^g([ei])||gh$1\nG||ng\nS||sh\nZ||zh\ni||ee\nI||i\ni$||e\nB||"+String.fromCharCode(664)+"\nT||"+String.fromCharCode(451)+"\nR||"+String.fromCharCode(450));$("#sing").val("IVN\nVS\nCVE\nSAV\nSAVE\nCV\nCVN");$("#syls").val("SV\nNV\nMV\nSAV\nSV\nSV\nNV\nMV\nSAV\nSVX\nMVX\nSAVX");$("#wrdi").val("SV\nIV\nAV\nCV\nSAV\nVX\nSV\nIV\nAV\nCV\nSAV\nVX\nAVX\nCVX\nIVX\nVX\nSAVX");$("#wrdf").val("MV\nMVE\nMV\nMVE\nSAV\nSAVE");$("#onetype,#slowsyl").prop("checked",
!1);$("#monoFrequent,#dropoffSlow").prop("checked",!0);break;default:return alert("Choose something from the list, first.")}syllablicChangeDetection($("#onetype")[0])}function loadPredef(){var a=$("#predef").val();defaultme(Number(a))}function syllablicChangeDetection(a){a.checked?($("#p_multi,.multiswap").hide(),$(".singleswap").show()):($("#p_multi,.multiswap").show(),$(".singleswap").hide())}zCounter=1;
$(document).ready(function(){"undefined"!==typeof Storage&&(Customizable=!0,null!==localStorage.getItem("CustomCats")&&(CustomInfo=!0,$("#predef").prepend('<option value="-1">Custom</option>'),$("#predef").val("-1"),defaultme(-1)));$("#onetype").change(function(){syllablicChangeDetection($("#onetype")[0])});syllablicChangeDetection($("#onetype")[0]);$(".help").click(function(){var a=$(this).find("span.info");if($(this).hasClass("popOut")){var c=$(this).attr("data-clicked");if("undefined"!==typeof c)$("#"+
c).remove(),$(this).removeAttr("data-clicked");else{var b=$(this).offset();var d=a.html();++zCounter;c="popup"+zCounter;$(this).attr("data-clicked",c);$("body").append('<div class="info" id="'+c+'"></div>');a=$("#"+c);a.toggle();c=b.left;var e=a.width()+20;var f=$(document).width();var g=c+$(this).width();g+e>f&&(c=g<=e?f<=e?c-g+2:c+(f-(g+e))-3:c-e);a.html(d).css({"z-index":zCounter,top:b.top+10,left:c});a.click(function(){$('span[data-clicked="'+$(this).attr("id")+'"]').removeAttr("data-clicked");
$(this).remove()})}}else a.toggle(),a.css("transform","translateX(0px)"),a.is(":visible")&&(++zCounter,a.css("z-index",zCounter),e=a.width()+20,f=$(document).width(),b=$(this).offset(),g=b.left+$(this).width(),g+e>f&&(g<=e?f<=e?a.css("transform","translateX("+(2-g)+"px)"):a.css("transform","translateX("+(f-g-e)+"px)"):a.css("transform","translateX("+(0-e)+"px)")))})});
